// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// login model
type LoginModel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginModel) Reset()         { *m = LoginModel{} }
func (m *LoginModel) String() string { return proto.CompactTextString(m) }
func (*LoginModel) ProtoMessage()    {}
func (*LoginModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginModel.Unmarshal(m, b)
}
func (m *LoginModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginModel.Marshal(b, m, deterministic)
}
func (m *LoginModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginModel.Merge(m, src)
}
func (m *LoginModel) XXX_Size() int {
	return xxx_messageInfo_LoginModel.Size(m)
}
func (m *LoginModel) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginModel.DiscardUnknown(m)
}

var xxx_messageInfo_LoginModel proto.InternalMessageInfo

func (m *LoginModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginModel) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginModel)(nil), "user.LoginModel")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x2d, 0x4e, 0x2d, 0x52, 0xf2, 0xe1,
	0xe2, 0xf2, 0x01, 0x09, 0xfa, 0xe6, 0xa7, 0xa4, 0xe6, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x89,
	0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0xcc, 0x60, 0x71, 0x38, 0xdf, 0xc8, 0x96, 0x8b, 0x07,
	0x6c, 0x5a, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x2e, 0x17, 0x2b, 0x98, 0x2f, 0x24,
	0xa0, 0x07, 0xb2, 0x4d, 0x0f, 0x61, 0x95, 0x14, 0x86, 0x88, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x65,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x96, 0x7e, 0xa5, 0xa8, 0x00, 0x00, 0x00,
}
