// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	// by search data
	GetBySearch(ctx context.Context, in *Request, opts ...client.CallOption) (*SearchData, error)
	// by id
	GetByID(ctx context.Context, in *ID, opts ...client.CallOption) (*User, error)
	// delete data
	Delete(ctx context.Context, in *ID, opts ...client.CallOption) (*Boolean, error)
	// update data
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Boolean, error)
	// create data
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*ID, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetBySearch(ctx context.Context, in *Request, opts ...client.CallOption) (*SearchData, error) {
	req := c.c.NewRequest(c.name, "UserService.GetBySearch", in)
	out := new(SearchData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetByID(ctx context.Context, in *ID, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.name, "UserService.GetByID", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Delete(ctx context.Context, in *ID, opts ...client.CallOption) (*Boolean, error) {
	req := c.c.NewRequest(c.name, "UserService.Delete", in)
	out := new(Boolean)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Boolean, error) {
	req := c.c.NewRequest(c.name, "UserService.Update", in)
	out := new(Boolean)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*ID, error) {
	req := c.c.NewRequest(c.name, "UserService.Create", in)
	out := new(ID)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// by search data
	GetBySearch(context.Context, *Request, *SearchData) error
	// by id
	GetByID(context.Context, *ID, *User) error
	// delete data
	Delete(context.Context, *ID, *Boolean) error
	// update data
	Update(context.Context, *Request, *Boolean) error
	// create data
	Create(context.Context, *Request, *ID) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetBySearch(ctx context.Context, in *Request, out *SearchData) error
		GetByID(ctx context.Context, in *ID, out *User) error
		Delete(ctx context.Context, in *ID, out *Boolean) error
		Update(ctx context.Context, in *Request, out *Boolean) error
		Create(ctx context.Context, in *Request, out *ID) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetBySearch(ctx context.Context, in *Request, out *SearchData) error {
	return h.UserServiceHandler.GetBySearch(ctx, in, out)
}

func (h *userServiceHandler) GetByID(ctx context.Context, in *ID, out *User) error {
	return h.UserServiceHandler.GetByID(ctx, in, out)
}

func (h *userServiceHandler) Delete(ctx context.Context, in *ID, out *Boolean) error {
	return h.UserServiceHandler.Delete(ctx, in, out)
}

func (h *userServiceHandler) Update(ctx context.Context, in *Request, out *Boolean) error {
	return h.UserServiceHandler.Update(ctx, in, out)
}

func (h *userServiceHandler) Create(ctx context.Context, in *Request, out *ID) error {
	return h.UserServiceHandler.Create(ctx, in, out)
}
