// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// user model
type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Headimg              string   `protobuf:"bytes,3,opt,name=headimg,proto3" json:"headimg,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Introduce            string   `protobuf:"bytes,5,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Createtime           string   `protobuf:"bytes,6,opt,name=createtime,proto3" json:"createtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetHeadimg() string {
	if m != nil {
		return m.Headimg
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

func (m *User) GetCreatetime() string {
	if m != nil {
		return m.Createtime
	}
	return ""
}

// search model
type SearchData struct {
	User []*User `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	// limit ?, ? sum data count
	SumPage              int64    `protobuf:"varint,2,opt,name=sumPage,proto3" json:"sumPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchData) Reset()         { *m = SearchData{} }
func (m *SearchData) String() string { return proto.CompactTextString(m) }
func (*SearchData) ProtoMessage()    {}
func (*SearchData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SearchData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchData.Unmarshal(m, b)
}
func (m *SearchData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchData.Marshal(b, m, deterministic)
}
func (m *SearchData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchData.Merge(m, src)
}
func (m *SearchData) XXX_Size() int {
	return xxx_messageInfo_SearchData.Size(m)
}
func (m *SearchData) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchData.DiscardUnknown(m)
}

var xxx_messageInfo_SearchData proto.InternalMessageInfo

func (m *SearchData) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SearchData) GetSumPage() int64 {
	if m != nil {
		return m.SumPage
	}
	return 0
}

// common request
type Request struct {
	Params               map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

// request
type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// true/false
type Boolean struct {
	Bool                 bool     `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boolean) Reset()         { *m = Boolean{} }
func (m *Boolean) String() string { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()    {}
func (*Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boolean.Unmarshal(m, b)
}
func (m *Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boolean.Marshal(b, m, deterministic)
}
func (m *Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boolean.Merge(m, src)
}
func (m *Boolean) XXX_Size() int {
	return xxx_messageInfo_Boolean.Size(m)
}
func (m *Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_Boolean proto.InternalMessageInfo

func (m *Boolean) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*SearchData)(nil), "user.searchData")
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterMapType((map[string]string)(nil), "user.Request.ParamsEntry")
	proto.RegisterType((*ID)(nil), "user.ID")
	proto.RegisterType((*Boolean)(nil), "user.Boolean")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xed, 0xd4, 0x49, 0x26, 0x02, 0x55, 0xa3, 0x1e, 0x96, 0x08, 0xaa, 0xb0, 0xbd, 0xf8,
	0x14, 0x41, 0xb9, 0x00, 0xc7, 0x62, 0x40, 0xb9, 0x55, 0x5b, 0xf5, 0x03, 0xb6, 0xf6, 0xa8, 0xb5,
	0xb0, 0xbd, 0x66, 0x77, 0xdd, 0x2a, 0x3f, 0xc3, 0x67, 0xf1, 0x3d, 0xc8, 0x63, 0xa7, 0x31, 0xe9,
	0x6d, 0xde, 0x7b, 0xe3, 0xe7, 0x37, 0xcf, 0x06, 0x68, 0x1d, 0xd9, 0x4d, 0x63, 0x8d, 0x37, 0x38,
	0xed, 0x66, 0xf9, 0x27, 0x80, 0xe9, 0xad, 0x23, 0x8b, 0xaf, 0x21, 0x2c, 0x72, 0x11, 0xac, 0x83,
	0x24, 0x52, 0x61, 0x91, 0x23, 0xc2, 0xb4, 0xd6, 0x15, 0x89, 0x70, 0x1d, 0x24, 0x0b, 0xc5, 0x33,
	0x0a, 0x98, 0x3d, 0x90, 0xce, 0x8b, 0xea, 0x5e, 0x44, 0x4c, 0xef, 0x21, 0xae, 0x60, 0xde, 0x68,
	0xe7, 0x9e, 0x8c, 0xcd, 0xc5, 0x94, 0xa5, 0x67, 0x8c, 0x6f, 0x61, 0x51, 0xd4, 0xde, 0x9a, 0xbc,
	0xcd, 0x48, 0x9c, 0xb0, 0x78, 0x20, 0xf0, 0x1c, 0x20, 0xb3, 0xa4, 0x3d, 0xf9, 0xa2, 0x22, 0x11,
	0xb3, 0x3c, 0x62, 0xe4, 0x0f, 0x00, 0x47, 0xda, 0x66, 0x0f, 0xa9, 0xf6, 0x1a, 0xcf, 0x81, 0x63,
	0x8b, 0x60, 0x1d, 0x25, 0xcb, 0x4b, 0xd8, 0xf0, 0x3d, 0x5d, 0x7e, 0xc5, 0x7c, 0x97, 0xd0, 0xb5,
	0xd5, 0xb5, 0xbe, 0xef, 0x83, 0x47, 0x6a, 0x0f, 0xe5, 0x13, 0xcc, 0x14, 0xfd, 0x6e, 0xc9, 0x79,
	0xfc, 0x08, 0x71, 0xa3, 0xad, 0xae, 0xdc, 0x60, 0xf3, 0xa6, 0xb7, 0x19, 0xe4, 0xcd, 0x35, 0x6b,
	0xdf, 0x6b, 0x6f, 0x77, 0x6a, 0x58, 0x5c, 0x7d, 0x81, 0xe5, 0x88, 0xc6, 0x53, 0x88, 0x7e, 0xd1,
	0x8e, 0xdb, 0x5a, 0xa8, 0x6e, 0xc4, 0x33, 0x38, 0x79, 0xd4, 0x65, 0xbb, 0xef, 0xab, 0x07, 0x5f,
	0xc3, 0xcf, 0x81, 0x3c, 0x83, 0x70, 0x9b, 0x1e, 0xd7, 0x2b, 0xdf, 0xc1, 0xec, 0xca, 0x98, 0x92,
	0x74, 0xdd, 0x35, 0x7d, 0x67, 0x4c, 0xc9, 0xe2, 0x5c, 0xf1, 0x7c, 0xf9, 0x37, 0x80, 0x65, 0x77,
	0xd6, 0x0d, 0xd9, 0xc7, 0x22, 0x23, 0xfc, 0x00, 0xcb, 0x9f, 0xe4, 0xaf, 0x76, 0x37, 0x5c, 0x05,
	0xbe, 0xfa, 0x2f, 0xf1, 0xea, 0xb4, 0x87, 0x87, 0x9e, 0xe4, 0x04, 0xdf, 0xc3, 0x8c, 0x9f, 0xd8,
	0xa6, 0x38, 0xef, 0xe5, 0x6d, 0xba, 0x1a, 0x15, 0x26, 0x27, 0x78, 0x01, 0x71, 0x4a, 0x25, 0x79,
	0x1a, 0x6d, 0x0c, 0xce, 0x43, 0x36, 0x39, 0xc1, 0x04, 0xe2, 0xdb, 0x26, 0xd7, 0x9e, 0x8e, 0x5f,
	0xfa, 0x62, 0xf3, 0x02, 0xe2, 0x6f, 0xfc, 0xdd, 0x8e, 0x37, 0x9f, 0xdd, 0xe5, 0xe4, 0x2e, 0xe6,
	0x9f, 0xef, 0xd3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xd1, 0x8b, 0xe7, 0x8a, 0x02, 0x00,
	0x00,
}
