// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package proto

import (
	proto1 "deercoder-chat/user-srv/proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Response struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

// message model
type Message struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUid              int64    `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	Headimg              string   `protobuf:"bytes,4,opt,name=headimg,proto3" json:"headimg,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ContentType          string   `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Message) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *Message) GetFromUid() int64 {
	if m != nil {
		return m.FromUid
	}
	return 0
}

func (m *Message) GetHeadimg() string {
	if m != nil {
		return m.Headimg
	}
	return ""
}

func (m *Message) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Message) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// uids
type UidS struct {
	Uids                 string   `protobuf:"bytes,1,opt,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidS) Reset()         { *m = UidS{} }
func (m *UidS) String() string { return proto.CompactTextString(m) }
func (*UidS) ProtoMessage()    {}
func (*UidS) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{3}
}

func (m *UidS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidS.Unmarshal(m, b)
}
func (m *UidS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidS.Marshal(b, m, deterministic)
}
func (m *UidS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidS.Merge(m, src)
}
func (m *UidS) XXX_Size() int {
	return xxx_messageInfo_UidS.Size(m)
}
func (m *UidS) XXX_DiscardUnknown() {
	xxx_messageInfo_UidS.DiscardUnknown(m)
}

var xxx_messageInfo_UidS proto.InternalMessageInfo

func (m *UidS) GetUids() string {
	if m != nil {
		return m.Uids
	}
	return ""
}

// true/false
type Boolean struct {
	Bool                 bool     `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boolean) Reset()         { *m = Boolean{} }
func (m *Boolean) String() string { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()    {}
func (*Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{4}
}

func (m *Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boolean.Unmarshal(m, b)
}
func (m *Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boolean.Marshal(b, m, deterministic)
}
func (m *Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boolean.Merge(m, src)
}
func (m *Boolean) XXX_Size() int {
	return xxx_messageInfo_Boolean.Size(m)
}
func (m *Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_Boolean proto.InternalMessageInfo

func (m *Boolean) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

// message array
type ArrayMessage struct {
	Message              []*Message `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ArrayMessage) Reset()         { *m = ArrayMessage{} }
func (m *ArrayMessage) String() string { return proto.CompactTextString(m) }
func (*ArrayMessage) ProtoMessage()    {}
func (*ArrayMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{5}
}

func (m *ArrayMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayMessage.Unmarshal(m, b)
}
func (m *ArrayMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayMessage.Marshal(b, m, deterministic)
}
func (m *ArrayMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayMessage.Merge(m, src)
}
func (m *ArrayMessage) XXX_Size() int {
	return xxx_messageInfo_ArrayMessage.Size(m)
}
func (m *ArrayMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayMessage proto.InternalMessageInfo

func (m *ArrayMessage) GetMessage() []*Message {
	if m != nil {
		return m.Message
	}
	return nil
}

// group user
type GroupUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId              string   `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupUser) Reset()         { *m = GroupUser{} }
func (m *GroupUser) String() string { return proto.CompactTextString(m) }
func (*GroupUser) ProtoMessage()    {}
func (*GroupUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{6}
}

func (m *GroupUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupUser.Unmarshal(m, b)
}
func (m *GroupUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupUser.Marshal(b, m, deterministic)
}
func (m *GroupUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupUser.Merge(m, src)
}
func (m *GroupUser) XXX_Size() int {
	return xxx_messageInfo_GroupUser.Size(m)
}
func (m *GroupUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupUser.DiscardUnknown(m)
}

var xxx_messageInfo_GroupUser proto.InternalMessageInfo

func (m *GroupUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupUser) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupUser) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// group response
type GUserResponse struct {
	GroupUser            []*GroupUser `protobuf:"bytes,1,rep,name=GroupUser,json=groupUser,proto3" json:"GroupUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GUserResponse) Reset()         { *m = GUserResponse{} }
func (m *GUserResponse) String() string { return proto.CompactTextString(m) }
func (*GUserResponse) ProtoMessage()    {}
func (*GUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{7}
}

func (m *GUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GUserResponse.Unmarshal(m, b)
}
func (m *GUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GUserResponse.Marshal(b, m, deterministic)
}
func (m *GUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GUserResponse.Merge(m, src)
}
func (m *GUserResponse) XXX_Size() int {
	return xxx_messageInfo_GUserResponse.Size(m)
}
func (m *GUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GUserResponse proto.InternalMessageInfo

func (m *GUserResponse) GetGroupUser() []*GroupUser {
	if m != nil {
		return m.GroupUser
	}
	return nil
}

// user list
type UserList struct {
	UserList             []*proto1.User `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{8}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUserList() []*proto1.User {
	if m != nil {
		return m.UserList
	}
	return nil
}

//
type ChatUser struct {
	User                 *proto1.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChatUser) Reset()         { *m = ChatUser{} }
func (m *ChatUser) String() string { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()    {}
func (*ChatUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{9}
}

func (m *ChatUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatUser.Unmarshal(m, b)
}
func (m *ChatUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatUser.Marshal(b, m, deterministic)
}
func (m *ChatUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatUser.Merge(m, src)
}
func (m *ChatUser) XXX_Size() int {
	return xxx_messageInfo_ChatUser.Size(m)
}
func (m *ChatUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatUser.DiscardUnknown(m)
}

var xxx_messageInfo_ChatUser proto.InternalMessageInfo

func (m *ChatUser) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*UidS)(nil), "proto.UidS")
	proto.RegisterType((*Boolean)(nil), "proto.Boolean")
	proto.RegisterType((*ArrayMessage)(nil), "proto.ArrayMessage")
	proto.RegisterType((*GroupUser)(nil), "proto.GroupUser")
	proto.RegisterType((*GUserResponse)(nil), "proto.GUserResponse")
	proto.RegisterType((*UserList)(nil), "proto.UserList")
	proto.RegisterType((*ChatUser)(nil), "proto.ChatUser")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xb4, 0x76, 0xc7, 0xa1, 0x89, 0x16, 0x0e, 0x26, 0x12, 0x50, 0xf6, 0x80, 0x22,
	0xa4, 0x26, 0x6d, 0x02, 0x22, 0x37, 0x54, 0x40, 0x0a, 0x48, 0xed, 0xc5, 0x69, 0xce, 0x91, 0x13,
	0x0f, 0xc9, 0x4a, 0x71, 0x6c, 0x76, 0xd7, 0x95, 0xf2, 0xa5, 0x7c, 0x02, 0xbf, 0x81, 0x76, 0xbc,
	0x36, 0x81, 0x56, 0x11, 0x3d, 0xed, 0xcc, 0x7b, 0xf3, 0x76, 0x67, 0xdf, 0x0c, 0xb4, 0x94, 0x96,
	0x18, 0x25, 0xfd, 0x4c, 0xa6, 0x3a, 0x65, 0x47, 0x74, 0x74, 0x7b, 0x31, 0xa2, 0x5c, 0xa6, 0x31,
	0xca, 0xf3, 0xe5, 0x3a, 0xd2, 0x83, 0x5c, 0xa1, 0x3c, 0x57, 0xf2, 0x6e, 0x40, 0x34, 0xa5, 0x85,
	0x80, 0x8f, 0xc0, 0x0d, 0xf1, 0x47, 0x8e, 0x4a, 0xb3, 0x1e, 0xb8, 0x09, 0x2a, 0x15, 0xad, 0x30,
	0x70, 0xce, 0x9c, 0x9e, 0x3f, 0x3c, 0x2d, 0x6a, 0xfa, 0x37, 0x05, 0x1a, 0x96, 0x34, 0x7f, 0x07,
	0x5e, 0x88, 0x2a, 0x4b, 0xb7, 0x0a, 0x1f, 0xa1, 0xfa, 0xe5, 0x80, 0x6b, 0x41, 0xc6, 0xa0, 0x99,
	0xe7, 0x22, 0x26, 0xc9, 0x49, 0x48, 0x31, 0x7b, 0x0e, 0xde, 0x4a, 0xa6, 0x79, 0x36, 0x17, 0x71,
	0x50, 0x27, 0xdc, 0xa5, 0xfc, 0x1b, 0x51, 0xdf, 0x65, 0x9a, 0xcc, 0x8d, 0xa4, 0x71, 0xe6, 0xf4,
	0x1a, 0xa1, 0x6b, 0xf2, 0x99, 0x88, 0x59, 0x00, 0xee, 0x1a, 0xa3, 0x58, 0x24, 0xab, 0xa0, 0x59,
	0x88, 0x6c, 0xca, 0xba, 0xe0, 0x99, 0x8f, 0x6e, 0xa3, 0x04, 0x83, 0x23, 0xa2, 0xaa, 0xdc, 0xa8,
	0x96, 0xe9, 0x56, 0xe3, 0x56, 0x07, 0xc7, 0x85, 0xca, 0xa6, 0xec, 0x35, 0xb4, 0x6c, 0x38, 0xd7,
	0xbb, 0x0c, 0x03, 0x97, 0x68, 0xdf, 0x62, 0xb7, 0xbb, 0x0c, 0xd9, 0x2b, 0xf0, 0x97, 0x12, 0x23,
	0x8d, 0x73, 0x2d, 0x12, 0x0c, 0x3c, 0xaa, 0x80, 0x02, 0xba, 0x15, 0x09, 0xf2, 0x2e, 0x34, 0x67,
	0x22, 0x9e, 0xd2, 0x2f, 0x45, 0xac, 0xaa, 0x5f, 0x8a, 0x58, 0xf1, 0x17, 0xe0, 0x7e, 0x4a, 0xd3,
	0x0d, 0x46, 0x5b, 0x43, 0x2f, 0xd2, 0x74, 0x43, 0xb4, 0x17, 0x52, 0xcc, 0xc7, 0xd0, 0xba, 0x92,
	0x32, 0xda, 0x95, 0x46, 0xfd, 0x65, 0x6f, 0xe3, 0x90, 0xbd, 0x5f, 0xe1, 0x64, 0x62, 0xec, 0x9a,
	0x29, 0x94, 0xec, 0x14, 0xea, 0xd6, 0xdd, 0x46, 0x58, 0x3f, 0xec, 0x6d, 0x07, 0x1a, 0x7f, 0x6c,
	0x35, 0x21, 0xff, 0x08, 0x4f, 0x26, 0xe6, 0x96, 0x6a, 0xc6, 0xfd, 0xbd, 0xab, 0x6d, 0x1b, 0x1d,
	0xdb, 0x46, 0x85, 0x87, 0x27, 0xab, 0x32, 0xe4, 0x43, 0xf0, 0xcc, 0x79, 0x2d, 0x94, 0x66, 0x6f,
	0x8a, 0x29, 0x98, 0xd8, 0x4a, 0xa1, 0x4f, 0xfb, 0x47, 0xa2, 0x8a, 0xe3, 0x6f, 0xc1, 0xfb, 0xbc,
	0x8e, 0x34, 0x75, 0xff, 0x12, 0x9a, 0x79, 0xf1, 0x94, 0xf3, 0x4f, 0x3d, 0xe1, 0xc3, 0x0c, 0xbc,
	0x29, 0x6d, 0x3d, 0x4a, 0x36, 0x80, 0xe3, 0x22, 0x66, 0xa5, 0x33, 0x76, 0x9f, 0xbb, 0xed, 0x2a,
	0x2f, 0xbe, 0xc1, 0x6b, 0x3d, 0xe7, 0xc2, 0x61, 0x23, 0x68, 0x4d, 0x51, 0xde, 0xa1, 0xfc, 0x6f,
	0xd9, 0x85, 0x33, 0xfc, 0x59, 0x07, 0xdf, 0xb4, 0x67, 0x94, 0x62, 0x89, 0xec, 0x12, 0xda, 0x5f,
	0x84, 0xd2, 0x52, 0x2c, 0x72, 0x8d, 0xe4, 0x01, 0xf3, 0xad, 0xce, 0x4c, 0xfe, 0x81, 0x4b, 0xd8,
	0x07, 0x38, 0x9d, 0xa0, 0xbe, 0xda, 0x6c, 0xa8, 0xfc, 0x46, 0xad, 0xee, 0xbd, 0xfc, 0xd4, 0xe6,
	0xfb, 0x0b, 0xc0, 0x6b, 0x6c, 0x0c, 0xed, 0x09, 0x6a, 0x52, 0x5d, 0x47, 0x4a, 0x3f, 0x42, 0xf9,
	0x1e, 0x3a, 0x21, 0x46, 0xf1, 0x41, 0xe9, 0x03, 0x9d, 0x8e, 0xa1, 0x55, 0x3e, 0x48, 0xe3, 0xb8,
	0x37, 0xeb, 0xee, 0xb3, 0x12, 0xd9, 0x5f, 0x13, 0x5e, 0x63, 0x97, 0xe0, 0x4f, 0x50, 0x57, 0xb3,
	0x2f, 0xef, 0x2e, 0x07, 0x5b, 0x3d, 0x56, 0x56, 0xf0, 0xda, 0xe2, 0x98, 0x90, 0xd1, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x80, 0x99, 0x15, 0x98, 0xc8, 0x04, 0x00, 0x00,
}
