// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: stream.proto

package proto

import (
	_ "deercoder-chat/user-srv/proto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Streamer service

type StreamerService interface {
	Stream(ctx context.Context, opts ...client.CallOption) (Streamer_StreamService, error)
	ServerStream(ctx context.Context, in *Request, opts ...client.CallOption) (Streamer_ServerStreamService, error)
}

type streamerService struct {
	c    client.Client
	name string
}

func NewStreamerService(name string, c client.Client) StreamerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &streamerService{
		c:    c,
		name: name,
	}
}

func (c *streamerService) Stream(ctx context.Context, opts ...client.CallOption) (Streamer_StreamService, error) {
	req := c.c.NewRequest(c.name, "Streamer.Stream", &Request{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &streamerServiceStream{stream}, nil
}

type Streamer_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Request) error
	Recv() (*Response, error)
}

type streamerServiceStream struct {
	stream client.Stream
}

func (x *streamerServiceStream) Close() error {
	return x.stream.Close()
}

func (x *streamerServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *streamerServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *streamerServiceStream) Send(m *Request) error {
	return x.stream.Send(m)
}

func (x *streamerServiceStream) Recv() (*Response, error) {
	m := new(Response)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamerService) ServerStream(ctx context.Context, in *Request, opts ...client.CallOption) (Streamer_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Streamer.ServerStream", &Request{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &streamerServiceServerStream{stream}, nil
}

type Streamer_ServerStreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*Response, error)
}

type streamerServiceServerStream struct {
	stream client.Stream
}

func (x *streamerServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *streamerServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *streamerServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *streamerServiceServerStream) Recv() (*Response, error) {
	m := new(Response)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Streamer service

type StreamerHandler interface {
	Stream(context.Context, Streamer_StreamStream) error
	ServerStream(context.Context, *Request, Streamer_ServerStreamStream) error
}

func RegisterStreamerHandler(s server.Server, hdlr StreamerHandler, opts ...server.HandlerOption) error {
	type streamer interface {
		Stream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
	}
	type Streamer struct {
		streamer
	}
	h := &streamerHandler{hdlr}
	return s.Handle(s.NewHandler(&Streamer{h}, opts...))
}

type streamerHandler struct {
	StreamerHandler
}

func (h *streamerHandler) Stream(ctx context.Context, stream server.Stream) error {
	return h.StreamerHandler.Stream(ctx, &streamerStreamStream{stream})
}

type Streamer_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Response) error
	Recv() (*Request, error)
}

type streamerStreamStream struct {
	stream server.Stream
}

func (x *streamerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *streamerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *streamerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *streamerStreamStream) Send(m *Response) error {
	return x.stream.Send(m)
}

func (x *streamerStreamStream) Recv() (*Request, error) {
	m := new(Request)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *streamerHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(Request)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.StreamerHandler.ServerStream(ctx, m, &streamerServerStreamStream{stream})
}

type Streamer_ServerStreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Response) error
}

type streamerServerStreamStream struct {
	stream server.Stream
}

func (x *streamerServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *streamerServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *streamerServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *streamerServerStreamStream) Send(m *Response) error {
	return x.stream.Send(m)
}

// Client API for ChatService service

type ChatService interface {
	// 创建群聊/好友
	DistributeGroup(ctx context.Context, in *UidS, opts ...client.CallOption) (*Response, error)
	// 拉取群聊所有消息
	GetAllGroupMsg(ctx context.Context, in *Request, opts ...client.CallOption) (*ArrayMessage, error)
	// 拉取离线信息
	GetGroupLastMsg(ctx context.Context, in *Request, opts ...client.CallOption) (*ArrayMessage, error)
	// 已读离线信息
	ReadGroupLastMsg(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取群聊用户列表
	GetGroupUser(ctx context.Context, in *GroupUser, opts ...client.CallOption) (*GUserResponse, error)
	// 获取用户好友列表
	// 直接用user.User problem
	GetUserList(ctx context.Context, in *ChatUser, opts ...client.CallOption) (*UserList, error)
}

type chatService struct {
	c    client.Client
	name string
}

func NewChatService(name string, c client.Client) ChatService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &chatService{
		c:    c,
		name: name,
	}
}

func (c *chatService) DistributeGroup(ctx context.Context, in *UidS, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ChatService.DistributeGroup", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService) GetAllGroupMsg(ctx context.Context, in *Request, opts ...client.CallOption) (*ArrayMessage, error) {
	req := c.c.NewRequest(c.name, "ChatService.GetAllGroupMsg", in)
	out := new(ArrayMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService) GetGroupLastMsg(ctx context.Context, in *Request, opts ...client.CallOption) (*ArrayMessage, error) {
	req := c.c.NewRequest(c.name, "ChatService.GetGroupLastMsg", in)
	out := new(ArrayMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService) ReadGroupLastMsg(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ChatService.ReadGroupLastMsg", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService) GetGroupUser(ctx context.Context, in *GroupUser, opts ...client.CallOption) (*GUserResponse, error) {
	req := c.c.NewRequest(c.name, "ChatService.GetGroupUser", in)
	out := new(GUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatService) GetUserList(ctx context.Context, in *ChatUser, opts ...client.CallOption) (*UserList, error) {
	req := c.c.NewRequest(c.name, "ChatService.GetUserList", in)
	out := new(UserList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChatService service

type ChatServiceHandler interface {
	// 创建群聊/好友
	DistributeGroup(context.Context, *UidS, *Response) error
	// 拉取群聊所有消息
	GetAllGroupMsg(context.Context, *Request, *ArrayMessage) error
	// 拉取离线信息
	GetGroupLastMsg(context.Context, *Request, *ArrayMessage) error
	// 已读离线信息
	ReadGroupLastMsg(context.Context, *Request, *Response) error
	// 获取群聊用户列表
	GetGroupUser(context.Context, *GroupUser, *GUserResponse) error
	// 获取用户好友列表
	// 直接用user.User problem
	GetUserList(context.Context, *ChatUser, *UserList) error
}

func RegisterChatServiceHandler(s server.Server, hdlr ChatServiceHandler, opts ...server.HandlerOption) error {
	type chatService interface {
		DistributeGroup(ctx context.Context, in *UidS, out *Response) error
		GetAllGroupMsg(ctx context.Context, in *Request, out *ArrayMessage) error
		GetGroupLastMsg(ctx context.Context, in *Request, out *ArrayMessage) error
		ReadGroupLastMsg(ctx context.Context, in *Request, out *Response) error
		GetGroupUser(ctx context.Context, in *GroupUser, out *GUserResponse) error
		GetUserList(ctx context.Context, in *ChatUser, out *UserList) error
	}
	type ChatService struct {
		chatService
	}
	h := &chatServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ChatService{h}, opts...))
}

type chatServiceHandler struct {
	ChatServiceHandler
}

func (h *chatServiceHandler) DistributeGroup(ctx context.Context, in *UidS, out *Response) error {
	return h.ChatServiceHandler.DistributeGroup(ctx, in, out)
}

func (h *chatServiceHandler) GetAllGroupMsg(ctx context.Context, in *Request, out *ArrayMessage) error {
	return h.ChatServiceHandler.GetAllGroupMsg(ctx, in, out)
}

func (h *chatServiceHandler) GetGroupLastMsg(ctx context.Context, in *Request, out *ArrayMessage) error {
	return h.ChatServiceHandler.GetGroupLastMsg(ctx, in, out)
}

func (h *chatServiceHandler) ReadGroupLastMsg(ctx context.Context, in *Request, out *Response) error {
	return h.ChatServiceHandler.ReadGroupLastMsg(ctx, in, out)
}

func (h *chatServiceHandler) GetGroupUser(ctx context.Context, in *GroupUser, out *GUserResponse) error {
	return h.ChatServiceHandler.GetGroupUser(ctx, in, out)
}

func (h *chatServiceHandler) GetUserList(ctx context.Context, in *ChatUser, out *UserList) error {
	return h.ChatServiceHandler.GetUserList(ctx, in, out)
}
