apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
    # 服务名
  name: api-gateway
spec:
  ports:
  - name: "8006"
    port: 8006
    targetPort: 8006
    # 对外通过nodePort暴露端口
    # 端口暴露范围30000~32767
    nodePort: 30006
  selector:
    io.kompose.service: api-gateway
  type: NodePort # NodePort方式暴露端口
status:
  loadBalancer: {}
