apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:deercoder-chat-api-gateway
        name: d-api
        ports:
        - containerPort: 8006
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-gateway
