apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    # 服务名
  name: api-gateway
spec:
  ports:
  - name: "8006"
    port: 8006
    targetPort: 8006
    # 对外通过nodePort暴露端口
    # 端口暴露范围30000~32767
    nodePort: 30006
  selector:
    app: api-gateway
  type: NodePort # NodePort方式暴露端口
