apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:deercoder-chat-api-gateway
        name: d-api
        ports:
        - containerPort: 8006
        resources: {}
      restartPolicy: Always
status: {}
