apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat-srv
  name: chat-srv
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: chat-srv
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:deercoder-chat-chat-srv
        name: d-chat
        ports:
        - containerPort: 8001
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: chat-srv
