apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consul
  name: consul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - image: consul
        name: d-consul
        ports:
        - containerPort: 8300
        - containerPort: 8301
        - containerPort: 8301
          protocol: UDP
        - containerPort: 8302
        - containerPort: 8302
          protocol: UDP
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 53
          protocol: UDP
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: consul
