apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: deercoder-chat
        - name: MYSQL_PASSWORD
          value: dreamlu
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_ROOT_PASSWORD
          value: dreamlu
        - name: MYSQL_USER
          value: dreamlu
        - name: TZ
          value: Asia/Shanghai
        image: mysql:5.7
        name: d-mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /bak
          name: mysql-claim0
      restartPolicy: Always
      volumes:
      - name: mysql-claim0
        hostPath:
          path: /root/deercoder-chat/bak
        #persistentVolumeClaim:
        #  claimName: mysql-claim0
  selector:
    matchLabels:
      app: mysql
