apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ../docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
  - name: "3306"
    # 这里改写了kompose生成的端口3308
    # k8s用 3306 替换 3308
    # 这里与docker-compose 概念不同
    # k8s集群内部访问端口, 也是配置文件的mysql连接端口
    # 区别：
    ## docker-compose 时配置文件的mysql连接端口依据targetPort对应
    ## k8s 时配置文件的mysql连接端口依据port端口
    port: 3306
    targetPort: 3306
    # mysql 对外暴露33060端口
    nodePort: 30060
  selector:
    io.kompose.service: mysql
  type: NodePort
status:
  loadBalancer: {}
