apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-srv
  name: user-srv
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: user-srv
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:deercoder-chat-user-srv
        name: d-user
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      app: user-srv
